#!/bin/bash

# Railway Deployment Guide - Interactive Script
# This will help you deploy your donation logger to Railway

echo "🚂 Railway Deployment Guide"
echo "============================"
echo ""

# Step 1: GitHub Setup
echo "📦 STEP 1: PUSH TO GITHUB"
echo "-------------------------"
echo ""
echo "Your code is ready to push! Follow these steps:"
echo ""
echo "1. Create a new GitHub repository:"
echo "   → Go to: https://github.com/new"
echo "   → Name: donation-logger"
echo "   → Private or Public (your choice)"
echo "   → DON'T add README, .gitignore, or license"
echo "   → Click 'Create repository'"
echo ""
echo "2. After creating, GitHub will show you commands."
echo "   Use the 'push an existing repository' section."
echo ""
echo "3. Your GitHub repository URL will look like:"
echo "   https://github.com/YOUR_USERNAME/donation-logger.git"
echo ""
read -p "Enter your GitHub username: " github_user
echo ""

if [ -z "$github_user" ]; then
    echo "❌ Username required!"
    exit 1
fi

REPO_URL="https://github.com/$github_user/donation-logger.git"

echo "Your repository URL: $REPO_URL"
echo ""
echo "Now run these commands:"
echo ""
echo "git remote add origin $REPO_URL"
echo "git push -u origin main"
echo ""
echo "⚠️  GitHub will ask for credentials:"
echo "   Username: $github_user"
echo "   Password: Use a Personal Access Token (NOT your password!)"
echo ""
echo "📝 To create a Personal Access Token:"
echo "   1. Go to: https://github.com/settings/tokens"
echo "   2. Click 'Generate new token (classic)'"
echo "   3. Give it a name: 'Railway Deployment'"
echo "   4. Check the 'repo' scope"
echo "   5. Click 'Generate token'"
echo "   6. COPY the token (you won't see it again!)"
echo "   7. Use this token as your password when pushing"
echo ""
read -p "Press ENTER when you've pushed to GitHub..."
echo ""

# Step 2: Railway Setup
echo "🚂 STEP 2: DEPLOY ON RAILWAY"
echo "----------------------------"
echo ""
echo "1. Go to: https://railway.app"
echo ""
echo "2. Click 'Login' → 'Login with GitHub'"
echo "   → Authorize Railway to access your GitHub"
echo ""
echo "3. Click 'New Project' (purple button)"
echo ""
echo "4. Select 'Deploy from GitHub repo'"
echo ""
echo "5. Choose 'donation-logger' from the list"
echo "   (If you don't see it, click 'Configure GitHub App' and give access)"
echo ""
echo "6. Railway will automatically start deploying!"
echo "   → It detects Node.js from package.json"
echo "   → Uses npm install and npm start"
echo "   → Everything is configured! ✅"
echo ""
read -p "Press ENTER when Railway shows your project dashboard..."
echo ""

# Step 3: Add Environment Variable
echo "🔧 STEP 3: ADD ENVIRONMENT VARIABLE"
echo "-----------------------------------"
echo ""
echo "In your Railway project dashboard:"
echo ""
echo "1. Click on your service (the donation-logger box)"
echo ""
echo "2. Click 'Variables' tab at the top"
echo ""
echo "3. Click 'New Variable' button"
echo ""
echo "4. Add this variable:"
echo "   Name:  DISCORD_WEBHOOK_URL"
echo "   Value: https://discord.com/api/webhooks/1486493175924261035/ixdzicHQ_zHsA1PTyRIx70zUjfkCkyaiGnY8lZFNm0ia4WSVE0UVtD_J1rKx5RyMfZBh"
echo ""
echo "5. Click 'Add' (Railway will automatically redeploy)"
echo ""
read -p "Press ENTER when you've added the environment variable..."
echo ""

# Step 4: Get URL
echo "🌐 STEP 4: GET YOUR PUBLIC URL"
echo "------------------------------"
echo ""
echo "1. In your Railway project, click 'Settings' tab"
echo ""
echo "2. Scroll to 'Networking' section"
echo ""
echo "3. Click 'Generate Domain'"
echo ""
echo "4. Railway will give you a URL like:"
echo "   https://donation-logger-production-xxxx.up.railway.app"
echo ""
echo "5. COPY THIS URL!"
echo ""
read -p "Paste your Railway URL here: " railway_url
echo ""

if [ -z "$railway_url" ]; then
    echo "⚠️  No URL provided, but you can continue manually"
    railway_url="https://your-app.up.railway.app"
fi

# Step 5: Test
echo "🧪 STEP 5: TEST YOUR API"
echo "-----------------------"
echo ""
echo "Test your deployed API:"
echo ""
echo "curl -X POST $railway_url/api/donation \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"playerName\": \"TestPlayer\","
echo "    \"userId\": 123456789,"
echo "    \"recipientName\": \"RecipientPlayer\","
echo "    \"recipientUserId\": 987654321,"
echo "    \"amount\": 50000,"
echo "    \"message\": \"Test from Railway!\""
echo "  }'"
echo ""
echo "Or use our test script:"
echo "./test-api.sh $railway_url"
echo ""
read -p "Press ENTER after testing (check Discord for the donation)..."
echo ""

# Step 6: Update Roblox
echo "🎮 STEP 6: UPDATE YOUR ROBLOX GAME"
echo "----------------------------------"
echo ""
echo "Open your Roblox game and update the API URL:"
echo ""
echo "1. Open Roblox Studio"
echo "2. Go to ServerScriptService → DonationSystem"
echo "3. Line 12, change the API_URL to:"
echo ""
echo "   local API_URL = \"$railway_url/api/donation\""
echo ""
echo "4. Save and publish your game"
echo ""
echo "5. Enable HTTP Requests:"
echo "   → Game Settings (Alt+S)"
echo "   → Security tab"
echo "   → Enable 'Allow HTTP Requests'"
echo "   → Save"
echo ""

# Done!
echo "✅ DEPLOYMENT COMPLETE!"
echo "======================="
echo ""
echo "Your donation logger is now live! 🎉"
echo ""
echo "📊 Summary:"
echo "  → API URL: $railway_url"
echo "  → Endpoint: $railway_url/api/donation"
echo "  → Health: $railway_url/health"
echo ""
echo "🎮 In Roblox:"
echo "  → Players press 'G' to open donation menu"
echo "  → Select recipient and amount"
echo "  → Donations appear in Discord with custom images!"
echo ""
echo "📈 Monitor your app:"
echo "  → Railway Dashboard: https://railway.app/project"
echo "  → View logs, metrics, and deployments"
echo ""
echo "🔄 Future Updates:"
echo "  Just push to GitHub:"
echo "    git add ."
echo "    git commit -m 'Updated features'"
echo "    git push"
echo "  Railway auto-deploys! 🚀"
echo ""
echo "Need help? Check the documentation:"
echo "  → START-HERE.md"
echo "  → MAKE-IT-PUBLIC.md"
echo "  → DEPLOYMENT.md"
echo ""
echo "🎉 Happy donations!"
